export const constants = {
	API_URL: 'http://localhost:5000/api',
	SEED: 'seed',
	REGION: 'region',
	MISTAKES_NUM: 'mistakes_num',
	locales: ['en', 'ru', 'pl', 'de'],
	countryLocal: ['USA', 'Россия', 'Poland', 'Deuschland'],
	MAX_SLIDER_MISTAKES: 10,
	STEP_SLIDER: 0.25,
	MIN_MISTAKES: 0,
	MAX_MISTAKES: 1000,
	MIN_SEED: 1,
	MAX_SEED: 9999999,
	STEP: 1,
	letters: [
		'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ ',
		'абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ ',
		'aąbcćdeęfghijklłmnńoópqrsśtuvwxyzźżAĄBCĆDEĘFGHIJKLŁMNŃOÓPQRSŚTUVWXYZŹŻ ',
		'aäbcdefghijklmnoöpqrstuüvwxyzAÄBCDEFGHIJKLMNOÖPQRSTUÜVWXYZ ',
	],
}
